### ISSUE TITLE
Documentation doesn't work

### ISSUE THREAD

**Issue by mjablecnik** [Flutterando/triple_pattern#116]
**Describe the bug**
Documentation doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/2686906/234495284-11e40794-f764-4b98-ae53-3877799f1a03.png)

**Comment by CristovoXDGM** [comment]
Docs still working @mjablecnik  , have you tried to find this part, maybe the docs have been updated https://triple.flutterando.com.br/docs/intro/getting-started

**Comment by mjablecnik** [comment]
I'm using `Link to doc` from pub.dev:
![image](https://user-images.githubusercontent.com/2686906/234560713-fe0b0c95-e115-4f66-8a2b-1dc26671a295.png)

There is not probably updated the link.

**Comment by mjablecnik** [comment]
And `View Example` link in README also doesn't work:
![image](https://user-images.githubusercontent.com/2686906/234561346-2c45a166-3cc0-4fa2-ac58-a268f3356d84.png)
