### ISSUE TITLE
[issue or question]Is delay in executeEither enough?

### ISSUE THREAD

**Issue by huang12zheng** [Flutterando/triple_pattern#20]
# in purpose
I read the source code about executeEither. it is wonderful. 
And I wonder if the user will only need delay? 

~delay is debounceTime in rx. However, throttleTime maybe someone need.~
debounceTime,or throttleTime maybe need

# some idea
code some mixinClass to implement executeEither with debounceTime?
But This not be a Simple API.Probably not a good choice

# detail
* in triple
```dart
Future<void> executeEither(Future<Either<Error, State>> Function() func, {Duration delay = const Duration(milliseconds: 50)}) async {
    final localTime = DateTime.now();
    _mutableObjects.lastExecution = localTime;
    await Future.delayed(delay);
    if (localTime != _mutableObjects.lastExecution) {
      return;
    }

    setLoading(true);

    await _mutableObjects.completerExecution?.cancel();

    _mutableObjects.completerExecution = CancelableOperation.fromFuture(func());

    await _mutableObjects.completerExecution!.then(
      (value) {
        if (value is Either<Error, State>) {
          value.fold(setError, update);
          setLoading(false);
        }
      },
    ).valueOrCancellation();
  }
```
* in bloc
```dart
@override
Stream<Transition<CounterEvent, int>> transformEvents(
  Stream<CounterEvent> events,
  TransitionFunction<CounterEvent, int> transitionFn,
) {
  return super.transformEvents(
    events.debounceTime(const Duration(milliseconds: 300)),   //<<<<
    transitionFn,
  );
}
```

**Comment by jacobaraujo7** [comment]
Hello.
That would be a shortcut to debounceTime and SwitchMap in Rx

**Comment by huang12zheng** [comment]
What I mean  is that there might be a custom change to the status, 
not just delayed to avoid duplicate clicks.

How do I control the frequency of executeEither occurring?
a shortcut by Rx doesn't look easy to do.

**Comment by jacobaraujo7** [comment]
Hi! I'll be thinking better about this function from now on
