### ISSUE TITLE
OnError opcional

### ISSUE THREAD

**Issue by toshiossada** [Flutterando/triple_pattern#22]
Poderia ser opcional o método onError, sendo assim quando for passado um Left(Error) mas meu widget não tiver o metodo OnError definido ele poderia por papdrão renderizar o onState por padrao. Desta forma se  eu quiser renderizar o mesmo widgete como o exemplo abaixo não precisarei repetir codigo.
![image](https://user-images.githubusercontent.com/2637049/111304919-1a720200-8635-11eb-8583-b530b486971f.png)
uma sugestão seria na hora q chamar o onError verificar se o widget.onError == null e chamar o onState
![image](https://user-images.githubusercontent.com/2637049/111305659-fd89fe80-8635-11eb-8b0a-3306c2059871.png)

**Comment by toshiossada** [comment]
https://github.com/Flutterando/triple_pattern/pull/23

**Comment by jacobaraujo7** [comment]
LGTM

**Comment by matheust3** [comment]
Quando uso setLoading(true) e depois setError().... Nao funciona chamar setLoading(false), a tela fica sempre no onLoading.
(Quando onError eh null)

**Comment by matheust3** [comment]
Quando onError eh null, a pagina fica soh no onLoading, mesmo chamando update no estado continua no onLoading ;(
