### ISSUE TITLE
Allow null state

### ISSUE THREAD

**Issue by AndreNeves97** [Flutterando/triple_pattern#24]
In some cases, I have a empty state in my screen. So I create a abstract class State, and to other classes EmptyState and MyState that implements It.

I'd like to set a null state to avoid creating the set of 3 classes mentioned above.

Thanks!

**Comment by jacobaraujo7** [comment]
I believe it is not interesting to have a nullable state. This is very complex to the standard, even considering that the situation that was introduced is pertinent.

Some sacrifices need to be made, one of them is to try to inhibit the maximum of nullable variables in this pattern, even if it costs some boilerplate.
