### ISSUE TITLE
Mais que um triple aninhado

### ISSUE THREAD

**Issue by mxaxs** [Flutterando/triple_pattern#29]
Pessoal, 
Empolgado com o triple!
Eu acompanhei com sucesso o exemplo 'SQUARE_COUNTER', com a adição de um Square_Store dentro do Home_Store. Mas não consegui entender se podemos ou não usar o Home_Store como centralizador de mais stores... Sem usar uma super classe ou mixin.

Como poderia ser possível, por exemplo:

 - Home_Store
             |___ Store_01
             |___ Store_02
             |___ ...
             |___ Store_n

Ou somente, assim? 
 ```
- Home_Store
       |__ Store_01
                |__ Store_02
                         |__ ...
                               |__ Store_n
```

**Comment by jacobaraujo7** [comment]
Olá!
Não há problema em receber outros Stores por injeção (Usando o Construtor).
Vc pode mockar Stores e usa-las em testes, por isso ainda se configura uma arquitetura de baixo acoplamento.

**Comment by mxaxs** [comment]
> Olá!
> Não há problema em receber outros Stores por injeção (Usando o Construtor).
> Vc pode mockar Stores e usa-las em testes, por isso ainda se configura uma arquitetura de baixo acoplamento.

Zero Pane @jacobaraujo7 !!! O triple está em vias de ir para produção por aqui. Mando notícias.

**Comment by jacobaraujo7** [comment]
Show de bola! 
Qualquer coisas estamos aqui!
