### ISSUE TITLE
Erros de digitação na doc

### ISSUE THREAD

**Issue by evandrmb** [Flutterando/triple_pattern#3]
Existem alguns erros de digitação na doc  como o método destroy que está como destory. 

Se importa se eu fizer uma PR corrigindo-os?😅

Também seria interessante adicionar a doc em inglês (devo abrir uma nova issue?) também abriria uma PR para ajudar!

**Comment by jacobaraujo7** [comment]
Nenhum pouco. O Inglês principalmete :)

**Comment by evandrmb** [comment]
Tudo bem. Estava em viagem, mas vou começar a trabalhar na PR! Obrigado pelo retorno.

**Comment by evandrmb** [comment]
Fechando a issue pois vi que foi dado merge na #5 que resolve essa issue :)
