### ISSUE TITLE
StreamStore não aceita um generic nulo

### ISSUE THREAD

**Issue by RenanWinter** [Flutterando/triple_pattern#30]
como fazer quando não temos um valor para setar no construtor vide exemplo abaixo?

![image](https://user-images.githubusercontent.com/7970199/114252687-eca28380-997c-11eb-980d-429f5df24ab0.png)

Neste caso apresenta o seguinte erro:
'ApiUser?' doesn't extend 'State extends Object'.
Try using a type that is or is a subclass of 'State extends Object'

**Comment by jacobaraujo7** [comment]
é proposital que o estado seja não nulo e imutável. Infelizmente não consigo obrigar que o usuário faça seu objeto que representará seu estado como imutável, mas consigo impetir que o estado seja null. 
Por favor, me conte um pouco mais no que faz sentido liberar o acesso ao nullo a variável de estado

**Comment by RenanWinter** [comment]
Estava estudando sobre gerência de estado na playlist Semana do Flutter - Gerência de Estado e entendi a necessidade de não permitir um valor nullo e sim criar uma estado que represente este valor nullo!

Obrigado pela resposta e bom trabalho!
