### ISSUE TITLE
setError não possibilita a leitura do StackTrace

### ISSUE THREAD

**Issue by paulosilva159** [Flutterando/triple_pattern#32]
Onde trabalho, repassamos o StackTrace para o FirebaseAnalytics. Ao tentar usar o triple, vi que apenas mexendo no código do próprio package eu poderia obter esse valor. Como não sei se essa é uma demanda válida, preferi abrir uma issue, ao invés de um PR, solicitando o acréscimo do StackTrace como parâmetro opcional ao chamar o setError

**Comment by jacobaraujo7** [comment]
Vc pode criar um objeto customizado onde o statetrance seja uma propriedade
