### ISSUE TITLE
Middleware não altera estado

### ISSUE THREAD

**Issue by paulosilva159** [Flutterando/triple_pattern#35]
Atualmente, se eu quiser colocar uma condicional no meu estado, teria que fazer isso junto ao método correspondente (increment, no caso da imagem). Contudo, isso não era pra ser uma responsabilidade do middleware? Ou passar isso no middleware quebraria algum dos princípios do SOLID?

![image](https://user-images.githubusercontent.com/36122105/117979649-87d6a200-b309-11eb-99db-0d49b1d4d956.png)

**Comment by williamsilva-98** [comment]
Você pode fazer a condicional no seu **controller** e alterar o estado no seu **store**.
