### ISSUE TITLE
Should have a pattern for initial state

### ISSUE THREAD

**Issue by carlosfiori** [Flutterando/triple_pattern#36]
For lists, the pattern works wonderfully, easy to understand and start, but for individual objects there is no "guidance" on how to initiate the store.
![code](https://user-images.githubusercontent.com/20682772/118001411-17398080-b31d-11eb-9b89-14dffa66f209.png)

**Comment by jacobaraujo7** [comment]
Hello!
For concrete class, you can create a empty factory to initial state. For example:
```
class ProductData {

factory ProductData.empty() => ProductData();
...
}
```

**Comment by cezar-pereira** [comment]
Not when use final and required attributs.
