### ISSUE TITLE
Solve Version mobx to 2.0.1

### ISSUE THREAD

**Issue by megaterrarc** [Flutterando/triple_pattern#37]
Because mobx_codegen >=2.0.1+2 depends on mobx ^2.0.1 and mobx_triple 1.0.2 depends on mobx 2.0.0, mobx_codegen >=2.0.1+2 is incompatible with mobx_triple 1.0.2.
And because no versions of mobx_triple match >1.0.2 <2.0.0, mobx_codegen >=2.0.1+2 is incompatible with mobx_triple ^1.0.2.
So, because mob_anst_flutter depends on both mobx_triple ^1.0.2 and mobx_codegen ^2.0.1+3, version solving failed.
pub get failed (1; So, because mob_anst_flutter depends on both mobx_triple ^1.0.2 and mobx_codegen ^2.0.1+3, version solving failed.)

**Comment by jacobaraujo7** [comment]
fixed
