### ISSUE TITLE
Problem with onLoading and onError in ScopedBuilder 

### ISSUE THREAD

**Issue by mjablecnik** [Flutterando/triple_pattern#42]
Hello, thank you for this package, it is very useful for me. :)

Now I am trying Modular with Triple package and I found that ScopedBuilder is not showing CirgularProgressIndikator during onLoading and Error message is also not showed during onLoading..
Normal state is showed OK when data are loaded without error.

My test project is here: https://github.com/mjablecnik/flutter_modular_boilerplate

Can you please look there and write me if I have something wrong or a bug if is something wrong in triple_pattern package?
In last commit you can see what I was changing: https://github.com/mjablecnik/flutter_modular_boilerplate/commit/5c8cb4c9bbb65b8d1795c3380b39e283c986af79
But my breakpoint is not stopped in onError function after throw exception.. 

Thank you very much.

**Comment by Bwolfs2** [comment]
Hi, i see ur project and apply some fixes...
u r not seting  setLoading(false); 
And the first loading was not appearing.... And i need to add a postCallback to make it work..

U can see a PR all the changes i made

**Comment by Bwolfs2** [comment]
But we are fixing this, cuz is not a normal behavior

**Comment by jacobaraujo7** [comment]
Fixed!
