### ISSUE TITLE
Question about StreamStore vs NotifierStore

### ISSUE THREAD

**Issue by mjablecnik** [Flutterando/triple_pattern#43]
Hello, thank you very much for your package. It is very useful for me. ;)

I see in flutter_triple that I can make stores with StreamStore or NotifierStore.
But I don't understand why you have two different type stores there.. why don't have only one?

Could you write me how much are different this 2 stores and in when I should use StreamStore and when NotifierStore? 
Or is it never mind when I use first or second store?

Thank you very much for your response. :)

**Comment by jacobaraujo7** [comment]
Thanks for the comment!
The difference is only in the reactivity.

Triple is a pattern that can be applied to any reactivity. If the developer thinks Streams is better then he will have a StreamStore, if he thinks ValueNotifier is better then we have ValueNotifier.

There is also a MobXStore :)

**Comment by mjablecnik** [comment]
Ok, thank you very much for your answer :)
