### ISSUE TITLE
[Question] melhor forma de inicializar o Store a partir de um dado Future

### ISSUE THREAD

**Issue by cindRoberta** [Flutterando/triple_pattern#60]
quero carregar vários books na tela ao acessar a página, como Dart não possui algo similar a top level await do Deno, qe possibilitaria facilmente converter Future<T> para T  fiz dessa forma:

```dart
class BooksRepository {
  static Future<List<BookModel>> get getAll => Future.value(books);
}

class BooksStore extends NotifierStore<Exception, List<BookModel>> {
  Future<void> setBooks(Future<List<BookModel>> bookRepository) async =>
      update(await bookRepository);

  BooksStore(Future<List<BookModel>> bookRepository) : super(<BookModel>[]) {
    setBooks(bookRepository);
  }
}
```

minha dúvida é, essa é a melhor forma de fazer, ou há alguma melhor, existe alguma forma de passar um Future diretamente para o super?

**Comment by Bwolfs2** [comment]
The best way is calling setBooks from initState of the Page/Widget =/
U can do this : ```update(bookRepository.getAll )```
