### ISSUE TITLE
This is not a question, it is a request for advice on page data sharing.

### ISSUE THREAD

**Issue by ismanong** [Flutterando/triple_pattern#67]
Hello.
First of all, thank you for your SSP framework, it is the best state expression I have seen for UI workers. May it become more and more popular.

However, I have a doubt.
I want to share data between pages and I have looked at all the examples of the project and there is no standard way to write it related.

So I put the Store instance on a static property of the global file. But I don't know if there are any special side effects of doing this.
![image](https://user-images.githubusercontent.com/13862699/145845843-51ccbb34-2457-48d2-810e-a426c1f57278.png)
![image](https://user-images.githubusercontent.com/13862699/145846065-58324879-1a9f-4d5c-a0d9-053cd3ba1761.png)
![image](https://user-images.githubusercontent.com/13862699/145846153-e2efaf69-349a-4d74-9ece-b447579b5e87.png)

However, after I did this, I tested all the possible cases of sharing data and found that it works, as long as the page is still on the Widget Tree, the ScopedBuilder class can always update to the new state again at the first time.

I'm a strict person and I like this mode of operation now, the functionality requires lots and lots of common data. But more than that, I'd like to know if it's rigorous to write it this way.

If you could have a better suggestion, or a more standard way to implement page sharing, as well as possibly performing page updates in some functions that don't depend on BuildContext. I would be very grateful for your help.

**Comment by mjablecnik** [comment]
I am using for this purpose Modular which is also developed by Flutterando developers and gives you an injection of your objects into pages or stores.

You only create Module file where you register your instances:
![image](https://user-images.githubusercontent.com/2686906/146273686-c6e28b4c-eab8-4c97-bc8e-401411f3dc24.png)

and then you gain it somewhere by command: `final userStore = Modular.get<UserStore>();`
without use of BuildContext.

More about Modular you can read from my short article: https://dev.to/mjablecnik/flutter-modular-architecture-2f15
And from documentation of this project: https://modular.flutterando.com.br/docs/intro
Modular have also some [Triple pattern integration](https://modular.flutterando.com.br/docs/flutter_modular/triple-integration) which can be useful for you when you are using Triple.

**Comment by ismanong** [comment]
Thanks, very clean structure that can be adapted to different stages of developers to understand the project.
