### ISSUE TITLE
Como utilizar @computed props em um MobXStore

### ISSUE THREAD

**Issue by diego-rangel** [Flutterando/triple_pattern#69]
**Describe the question**
Qual seria a melhor forma de se ter props computadas dentro de uma classe MobStore, uma vez que se adicionadas, temos o seguinte warning: "This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final".

**Comment by jacobaraujo7** [comment]
Olá. Desculpe a demora. (férias)

- Vc pode usar os selectors em um getter que irá funcionar. 
Abraços.
https://triple.flutterando.com.br/docs/getting-started/using-flutter-triple#selectors
