### ISSUE TITLE
Typo in `/docs/intro/` page

### ISSUE THREAD

**Issue by LSViana** [Flutterando/triple_pattern#75]
### Question

The quote that explains what the acronym "BLoC" means has a typo in the word "Bussines":

> IMPORTANT: BLoC is an acronym for **Bussines** Logic Component.

### Expected behavior

The word should be written as "Business".

**Comment by LSViana** [comment]
There are also some other writing issues on this page, I've reported #74 already and I'm planning to open more issues.

However, I'm not sure if that's the best way to proceed, it seems very granular and it'll introduce lots of overhead just to fix a few typos. Would it be better if I submitted a single PR with all the fixes I consider pertinent?

**Comment by jacobaraujo7** [comment]
Thanks!
