### ISSUE TITLE
Better pub.dev presentation

### ISSUE THREAD

**Issue by Pierre2tm** [Flutterando/triple_pattern#76]
**Better pub dev presentation**
Triple has a lot of potential, but with so many state management packages available, it needs some marketing. Having to dig into the docs to see what the package does may discourage users. A minimal introduction to pub.dev could be beneficial to the adoption of the package.

**Solution**
Add minimal code exemples on readme instead of just redirecting to the doc.
Presenting the concept of TSP shortly could be nice too.
Maybe end with killer features (hydrated, undo/redo ?) presentation and a link to the doc ?
However, we should be carefull to not overhelm the reader !

Regards

**Comment by Pierre2tm** [comment]
It's my fault, I didn't see that there was a description in the "triple" package.
However, I think this still applies to the "flutter_triple" package since users (like me) can land directly on flutter_triple without seeing triple package.

**Comment by Bwolfs2** [comment]
Added: https://pub.dev/packages/flutter_triple/example

**Comment by Bwolfs2** [comment]
@Pierre2tm if u have any other suggest, we are open to hear =)
