### ISSUE TITLE
How to use multiple store

### ISSUE THREAD

**Issue by cyclothunder** [Flutterando/triple_pattern#96]
Hi,
How can I use multiple store on a view?

For example:

```
final counter = CounterStore();
final otherCounter = OtherCounter();
```

Reading through documentation in Observers and Builders, those examples use only one store, like the ScopedBuilder for instance.

```
ScopedBuilder(
    store: counter,
    onState: (context, state) => Text('$state'),
    onError: (context, error) => Text(error.toString()),
    onLoading: (context) => CircularProgressIndicator(),
);
```

**Comment by tauamendonca** [comment]
For now there's no such option natively in Triple (and thank you for pointing out, we are looking and discussing about it's implementation).

It's not advised, because it can lead to some issues, but you could use a ScopedBuilder inside another ScopedBuilder and it can work.
